---

version: '3'
services:
  app:
    build: .
    ports:
      - 5001:5001
    command: gunicorn -w 3 -b 0.0.0.0:5001 --chdir /app wsgi:app

  mongodb:
    build: ./mongodb/
    ports: 
      - 27017:27017
    environment:
      - MONGO_INIT_DB_ROOT_USERNAME=admin
      - MONGO_INIT_DB_ROOT_PASSWORD=password

  mongo-express:
    image: mongo-express:0.54.0
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
